# Continuos Integration workflow for testing pushed commits and pull requests
name: E2E test CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install and test the applications
        # Install the apps using npm ci (ensures a clean install)
        # Run the test script executing the e2e tests for the gateway service
        # The script will run the relevant microservices in the abckground, wait for them to start (30 seconds), then run the tests
        run: |
          npm install
          npm run test:e2e:ci
